class ErrorCode:
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_FILE = "INVALID_FILE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    UNSUPPORTED_IMAGE_FORMAT = "UNSUPPORTED_IMAGE_FORMAT"
    IMAGE_DECODE_FAILED = "IMAGE_DECODE_FAILED"
    IMAGE_DIMENSIONS_TOO_LARGE = "IMAGE_DIMENSIONS_TOO_LARGE"
    IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND"
    INVALID_COLOR = "INVALID_COLOR"
    INVALID_PALETTE = "INVALID_PALETTE"
    INVALID_RATIO = "INVALID_RATIO"
    INVALID_STRENGTH = "INVALID_STRENGTH"
    NOT_FOUND = "NOT_FOUND"
    STORAGE_UPLOAD_FAILED = "STORAGE_UPLOAD_FAILED"
    STORAGE_DOWNLOAD_FAILED = "STORAGE_DOWNLOAD_FAILED"
    STORAGE_DELETE_FAILED = "STORAGE_DELETE_FAILED"
    STORAGE_CONNECTION_FAILED = "STORAGE_CONNECTION_FAILED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


class AppError(Exception):
    def __init__(
        self,
        code: str,
        message: str,
        status_code: int,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.status_code = status_code
